version: '3.3'
services:
  
  app: 
    hostname: ${HOSTNAME}
    network_mode: "host"
    build: 
      context: .
      dockerfile: dockerfile
    ports: 
      - "8080:8080"
  
  db:
    image: mongo
    ports:
      - "8001:27017"
    restart: unless-stopped
    env_file: .env
