version: "3.9" 

services:

   web:

       build: .

       ports:

           - "8080:8080"

       environment:

           DB_URI=${DB_URI}
           CITY_DB=${CITY_DB}
           COL_USER=${COL_USER}
           COL_CITY=${COL_CITY}